apiVersion: apps/v1
kind: Deployment
metadata:
  name: basickube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: basickube
  template:
    metadata:
      labels:
        app: basickube
    spec:
      containers:
      - name: basickube
        image: basickube/basickube:latest
        ports:
        - containerPort: 8080
