apiVersion: apps/v1
kind: Deployment
metadata:
  name: basickube
spec:
  replicas: 2
  selector:
    matchLabels:
      app: basickube
  template:
    metadata:
      labels:
        app: basickube
    spec:
      nodeSelector:
        agentpool: smallsystem
      containers:
        - name: basickube
          image: dbabych/basickube:latest
          ports:
            - containerPort: 8080
      tolerations:
      - key: "mode"
        operator: "Equal"
        value: "user"
        effect: "NoSchedule"