apiVersion: apps/v1
kind: Deployment
metadata:
name: myproject-api
spec:
replicas: 1
selector:
matchLabels:
app: myproject-api
template:
metadata:
labels:
app: myproject-api
spec:
containers:
- name: api
image: dockerhubuser/myproject:latest
ports:
- containerPort: 80