apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: basickube-ingress
  namespace: basickube-ns
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: $INGRESS_IP
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: basickube-service
            port:
              number: 80
