apiVersion: v1
kind: Service
metadata:
  name: basickube-service
  namespace: basickube-ns
spec:
  type: ClusterIP
  selector:
    app: basickube
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
