apiVersion: v1
kind: Service
metadata:
  name: basickube-service
  namespace: basickube-ns
spec:
  selector:
    app: basickube
  ports:
    - protocol: TCP
      port: 80       # external service port
      targetPort: 80 # must match containerPort
